# Generated by Django 3.2.5 on 2021-08-07 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', help_text='Nombre de la fotografia a mostrar. (Solo es informativo para el administrador)', max_length=60, verbose_name='Nombre de la imagen')),
                ('image', models.ImageField(height_field=202, upload_to='gallery', width_field=360)),
                ('created_on', models.DateTimeField(auto_now_add=True, help_text='Fecha en la que se registró la imágen en el sistema', verbose_name='Fecha de registro')),
                ('updated_on', models.DateTimeField(auto_now_add=True, help_text='Fecha en la que la imágen se actualizó por última vez', verbose_name='Fecha de actualización')),
            ],
        ),
    ]
