# Generated by Django 3.2.5 on 2021-08-07 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(help_text='Se recomiendan imagenes rectangulares', upload_to='gallery', verbose_name='Imagen a mostrar'),
        ),
    ]
