# Generated by Django 3.2.5 on 2021-08-02 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projects', verbose_name='Foto del proyecto')),
                ('name', models.CharField(default='', help_text='Ingrese el nombre del proyecto', max_length=50, unique=True, verbose_name='Nombre del proyecto')),
                ('description', models.TextField(default='', help_text='Ingrese una descripción corta del proyecto.', verbose_name='Descripción corta del proyecto')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Creado el: ')),
                ('updated_on', models.DateTimeField(auto_now_add=True, verbose_name='Actualizado el: ')),
            ],
            options={
                'verbose_name': 'Proyecto de portafolio',
                'verbose_name_plural': 'Proyectos del portafolio',
                'ordering': ['created_on'],
            },
        ),
    ]
